### ISSUE TITLE
posting examples

### ISSUE THREAD

**Issue by iam-peekay** [sheepsteak/react-shallow-testutils#14]
Hi @sheepsteak. I was hoping to ask if you might be able to post some examples in your README. The docs are a bit unclear for a beginner. For example, I'm following your instructions for 
```
boolean isComponentOfType(ReactComponent component, function componentClass)
```
but I keep getting false. When I console log the component, I get the right instance but I'm not sure if I'm calling the function incorrectly. Here's what I'm doing: 

```
import { expect } from 'chai';
import React from 'react';
import ReactTestUtils from 'react-addons-test-utils';
import ShallowTestUtils from 'react-shallow-testutils';
import Chart from '../chart.jsx';
import BarChart from '../Charts/BarChart/barChart.jsx';

describe('BarChart', function() {

  beforeEach(() => {
    this.renderer = ReactTestUtils.createRenderer();
    this.renderer.render(<BarChart />, context);
    this.result = this.renderer.getRenderOutput()
  });

  it("renders the BarChart component", () => {
    const barChart = ShallowTestUtils.getMountedInstance(this.renderer);
    expect(ShallowTestUtils.isComponentOfType(barChart, BarChart)).to.be.true;
  });
});
```
But the test fails. 

However, when I console.log(barChart), I get the proper BarChart component: 
![image](https://cloud.githubusercontent.com/assets/5421194/12014297/ba67e99a-acde-11e5-9202-208ae4b6b45b.png)

would love any help!

**Comment by sheepsteak** [comment]
Hi, the `getMountedInstance` function only needs to be used if you want the *actual* backing component (so you could then call functions on your `BarChart` component like `forceUpdate` for example).

I'll work on adding some examples but as stated in the README but for now you can look at the [tests](https://github.com/sheepsteak/react-shallow-testutils/tree/master/specs) for examples.

**Comment by iam-peekay** [comment]
@sheepsteak great, i'll look at the tests. thanks!

**Comment by sheepsteak** [comment]
README has been updated with some examples.
