### ISSUE TITLE
Latest npm package points to 0.4

### ISSUE THREAD

**Issue by ianmcnally** [sheepsteak/react-shallow-testutils#21]
Hi Sheepsteak,

Awesome library, it's been very helpful.

On my first install, with `npm i -D react-shallow-testutils`, I received version 0.4 which supports React <= 0.13. I initially attributed this to a bug in this repo, though I couldn't see any problems with the code on master (the import of `react/addons` was the offending line). Eventually I realized that because I'm on React 0.14 I would need to install 0.5+.

It seems safe enough to assume users of this lib are on React 0.14 so the latest package could be 0.5+ (maybe 1.0?), to make sure new users don't trip on versioning issues. Thought I'd drop by to mention it, in case you agree. Cheers!

**Comment by sheepsteak** [comment]
Sorry! I fixed #11 in the 0.4.x version that supports React 0.13 and published it. Looks like I fell prey to this npm/npm#6778 issue. I'll update the `latest` tag to point to the newest `1.0.0`. Thanks!

**Comment by ianmcnally** [comment]
Wicked, thanks!
