### ISSUE TITLE
Docs say `ReactComponent` when it is actually `ReactElement`

### ISSUE THREAD

**Issue by aaronbeall** [sheepsteak/react-shallow-testutils#24]
Throughout the documentation and the source it refers to input as being a `ReactComponent`, but it actually is a `ReactElement`. 

For example, the docs for `findWithType` show:

    ReactComponent findWithType(ReactComponent tree, function componentClass | string tagName)

With the example:

    const renderer = ReactTestUtils.createRenderer();

    renderer.render(<MyComponent />);
    expect(findWithType(renderer.getRenderOutput(), MyOtherComponent)).not.toThrow();

However, `renderer.getRenderOutput()` returns a `ReactElement`, _not_ a `ReactComponent`.

I found this rather confusing, since the primary issue with `ReactTestUtils` when using `ShallowRenderer` is that the `find/scry` functions do not support searching a `ReactElement`, only a `ReactComponent`.

**Comment by sheepsteak** [comment]
Thanks for pointing this out. I completely missed it when updating the README recently. You're right, the first parameter to these functions should be `ReactElement`.

As for what is returned by `getRenderOutput()`, I was never actually sure what it was. The [documentation](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) is very short!

**Comment by aaronbeall** [comment]
Yep I agree the documentation sure is lacking! I was able to figure most of this out by using TypeScript (`react.d.ts` definition file). I wrote a definition file for this library.

**Comment by sheepsteak** [comment]
Oh great! I don't use TypeScript myself but I understand it's definitions can be used with Flow. Is that right? I'll check it out, thanks.

**Comment by sheepsteak** [comment]
[Looks like I was wrong](https://github.com/facebook/flow/issues/7) but it might get implemented.
